deployment:
  enabled: true
replicaCount: 1
serviceAccount:
  create: true
  name: "cartservice"
image:
  repository: 797226340543.dkr.ecr.ap-southeast-1.amazonaws.com/cartservice
  tag: "b6416b0a40885c63f7047a872ccdd1272cf1bd4c"
  pullPolicy: Always
service:
  enabled: true
  type: ClusterIP
  port: 7070
  targetPort: 7070
env:
  REDIS_ADDR: "redis-cart-dev:6379"
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 64Mi
probes:
  readiness:
    grpc:
      port: 7070
    initialDelaySeconds: 15
    periodSeconds: 15
  liveness:
    grpc:
      port: 7070
    initialDelaySeconds: 15
    periodSeconds: 15
networkPolicy:
  allowFrom:
    - frontend-dev
    - checkoutservice-dev
