deployment: 
  enabled: true

replicaCount: 1

serviceAccount:
  create: true
  name: "checkoutservice"

image:
  repository: 797226340543.dkr.ecr.ap-southeast-1.amazonaws.com/checkoutservice
  tag: "local"
  pullPolicy: Always

service:
  enabled: true
  type: ClusterIP
  port: 5050
  targetPort: 5050

env:
  PORT: "5050"
  SHIPPING_SERVICE_ADDR: "shippingservice-dev:50051"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice-dev:3550"
  CART_SERVICE_ADDR: "cartservice-dev:7070"
  CURRENCY_SERVICE_ADDR: "currencyservice-dev:7000"
  EMAIL_SERVICE_ADDR: "emailservice-dev:8080"
  PAYMENT_SERVICE_ADDR: "paymentservice-dev:50051"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
    
probes:
  readiness:
    grpc:
      port: 5050
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    grpc:
      port: 5050
    initialDelaySeconds: 20
    periodSeconds: 10
networkPolicy:
  allowFrom:
    - frontend-dev
