deployment:
  enabled: true
replicaCount: 1
serviceAccount:
  create: true
  name: "emailservice"
image:
  repository: 445817183958.dkr.ecr.ap-southeast-1.amazonaws.com/emailservice
  tag: "18da8f445f90cf00ebb100c9e9983639a4f5eaae"
  pullPolicy: Always
service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
env:
  PORT: "8080"
  ENABLE_TRACING: "1"
  DISABLE_PROFILER: "1"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
probes:
  readiness:
    grpc:
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 20
  liveness:
    grpc:
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 20
networkPolicy:
  allowFrom:
    - checkoutservice-dev
