deployment: 
  enabled: true

replicaCount: 1

serviceAccount:
  create: true
  name: "productcatalogservice"

image:
  repository: 797226340543.dkr.ecr.ap-southeast-1.amazonaws.com/productcatalogservice
  tag: "local"
  pullPolicy: Always

service:
  enabled: true
  type: ClusterIP
  port: 3550
  targetPort: 3550

env:
  PORT: "3550"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
    
probes:
  readiness:
    grpc:
      port: 3550
    initialDelaySeconds: 20
    periodSeconds: 20
  liveness:
    grpc:
      port: 3550
    initialDelaySeconds: 20
    periodSeconds: 20
networkPolicy:
  allowFrom:
    - frontend-dev
    - checkoutservice-dev
    - recommendationservice-dev
