deployment:
  enabled: true

replicaCount: 1

serviceAccount:
  create: true
  name: "currencyservice"

image:
  repository: currencyservice
  tag: "local"
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  port: 7000
  targetPort: 7000

env:
  PORT: "7000"
  ENABLE_TRACING: "1"
  DISABLE_PROFILER: "1"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
    
probes:
  readiness:
    grpc:
      port: 7000
    initialDelaySeconds: 20
    periodSeconds: 15
  liveness:
    grpc:
      port: 7000
    initialDelaySeconds: 20
    periodSeconds: 15
networkPolicy:
  allowFrom:
    - frontend
    - checkoutservice
