deployment: 
  enabled: true

replicaCount: 1

serviceAccount:
  create: true
  name: "adservice"

image:
  repository: adservice
  tag: "local"
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  port: 9555
  targetPort: 9555
env:
  PORT: "9555"

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 180Mi

probes:
  readiness:
    grpc:
      port: 9555
    initialDelaySeconds: 20
    periodSeconds: 20
  liveness:
    grpc:
      port: 9555
    initialDelaySeconds: 20
    periodSeconds: 20
networkPolicy:
  allowFrom:
    - frontend
