deployment: 
  enabled: true

replicaCount: 1

serviceAccount:
  create: true
  name: "shippingservice"

image:
  repository: shippingservice
  tag: "local"
  pullPolicy: Never

service:
  enabled: true
  type: ClusterIP
  port: 50051
  targetPort: 50051

env:
  PORT: "50051"
  ENABLE_TRACING: ""
  DISABLE_PROFILER: "1"
  DISABLE_STATS: ""

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  readiness:
    grpc:
      port: 50051
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    grpc:
      port: 50051
    initialDelaySeconds: 20
    periodSeconds: 10
networkPolicy:
  allowFrom:
    - frontend
    - checkoutservice
