apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-microservices

namePrefix: local-
labels:
  - pairs:
      env: local
      project: microservices-demo
    includeSelectors: true

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - path: checkoutservice-patch.yaml
  - path: frontend-patch.yaml
  - path: recommendationservice-patch.yaml
  - path: cartservice-patch.yaml