apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: cartservice 
      containers:
        - name: cartservice
          image: cartservice:local
          imagePullPolicy: Always 
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: cartservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      volumes:
        - name: redis-data
          emptyDir: {}
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 200m
              memory: 128Mi  
            requests:
              cpu: 100m       
              memory: 64Mi    
          readinessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            periodSeconds: 10
          volumeMounts:
            - name: redis-data
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  selector:
    app: redis-cart
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379